### ISSUE TITLE
Implement contextualised suggestions for config actions

### ISSUE THREAD

**Issue by marcelovani** [marcelovani/drupal-recipes-autocomplete-vscode#1]
Task: Provide autocomplete for config actions. The suggestions need to be relevant to the config, example:

```yaml
config:
  actions:
    user.role.editor:
      createIfNotExists: <- Contextual suggestion
        label: 'Editor'
      grantPermissions:  <- Contextual suggestion
        - 'delete any article content' <- Dynamic suggestions
        - 'edit any article content'
```

In the example above, the list of suggestions for `user.role.editor` should include `createIfNotExists`, `grantPermissions`, etc.

In terms of autocomplete options, they can be found in this repository https://git.drupalcode.org/project/distributions_recipes/-/tree/1.0.x/docs

Ideally this should be implemented using schemas as suggested here https://www.drupal.org/project/distributions_recipes/issues/3475786

Task
- Update the schema for `drupal-recipe.json` on (SchemaStore)[https://github.com/SchemaStore/schemastore]
