### ISSUE TITLE
Implement dynamic suggestions for config actions

### ISSUE THREAD

**Issue by marcelovani** [marcelovani/drupal-recipes-autocomplete-vscode#7]
On https://github.com/marcelovani/drupal-recipes-autocomplete-vscode/issues/1 we implemented suggestions for contextualised actions. These suggestions work based on Json Schema.

Now we need to implement the dynamic parts i.e.

```yaml
config:
  actions:
      user.role.authenticated:
      grantPermissions:
        - 'access help pages' <- Dynamic items
        - 'access shortcuts'
        - 'access user profiles'
        - 'delete own files'
        - 'use advanced search'
        - 'view own unpublished content'
```
